system:
  redis-l3: false
spring:
  data:
    redis:
      # Redis 模式: single(单机), cluster(集群), sentinel(哨兵)
      mode: ${REDIS_MODE:single}
      
      # ==================== 单机模式配置 ====================
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:redispwd}
      
      # ==================== 集群模式配置 ====================
      cluster:
        # 集群节点，逗号分隔，例如: 192.168.1.1:6379,192.168.1.2:6379,192.168.1.3:6379
        nodes: ${REDIS_CLUSTER_NODES:}
        # 扫描间隔，单位毫秒
        scan-interval: 2000
        # 读模式: SLAVE(从节点读), MASTER(主节点读), MASTER_SLAVE(主从都读)
        read-mode: SLAVE
      
      # ==================== 哨兵模式配置 ====================
      sentinel:
        # 主节点名称
        master: ${REDIS_SENTINEL_MASTER:}
        # 哨兵节点，逗号分隔，例如: 192.168.1.1:26379,192.168.1.2:26379,192.168.1.3:26379
        nodes: ${REDIS_SENTINEL_NODES:}
      
      # ==================== 连接池配置 ====================
      pool:
        # 连接池大小
        connection-pool-size: 64
        # 最小空闲连接数
        connection-minimum-idle-size: 10
        # 空闲连接超时时间（毫秒）
        idle-connection-timeout: 10000
        # 连接超时时间（毫秒）
        connect-timeout: 10000
        # 命令等待超时（毫秒）
        timeout: 3000