server:
  port: 9527
  compression:
    enabled: true
spring:
  application:
    name: gateway
  config:
    import:
      - optional:classpath:git.properties
      - optional:classpath:META-INF/build-info.properties
      - optional:file:./META-INF/build-info.properties
      - optional:file:./application/META-INF/build-info.properties
  profiles:
    active:
      - actuator
      - discovery
      - discovery-impl
      - loadbalancer
      - logger
      - micrometer
      - redis
      - sa-token